export const DEFAULT_EXPENSE_CATEGORIES = {
  ADMINISTRATION: [
    'Furniture Purchase',
    'Office Rent',
    'Printing',
    'Security Services',
    'Stationery',
  ],
  FINANCE: [
    'Audit Fees',
    'Bank Charges',
    'Insurance Premium',
    'Legal Fees',
    'Tax Filing',
  ],
  HRM: [
    'Employee Engagement',
    'Job Portal Subscription',
    'Recruitment Cost',
    'Training Program',
  ],
  MARKETING: [
    'Email Marketing',
    'Event Sponsorship',
    'Facebook Ads',
    'Google Ads',
    'LinkedIn Campaign',
  ],
  OPERATION: [
    'Courier Charges',
    'Electricity Bill',
    'Internet Charges',
    'Office Maintenance',
    'Pantry Expenses',
  ],
  OTHERS: [
    'Donations',
    'Emergency Expenses',
    'Miscellaneous Expenses',
    'Repairs',
  ],
  SALARY: [
    'Bonus Payment',
    'Employee Salary',
    'Incentive Payout',
    'Overtime Payment',
  ],
  SALES: [
    'Client Meeting',
    'Hotel Stay',
    'Lead Purchase',
    'Sales Incentives',
    'Travel Expenses',
  ],
  SOFTWARE: [
    'AWS Cloud',
    'Antivirus Renewal',
    'Azure Subscription',
    'Microsoft License',
    'Power BI Pro',
    'Tableau License',
  ],
};
