export const DEFAULT_EXPENSE_CATEGORIES = {
  'Operation Expenses': [
    'Advertisement Expenses',
    'LMS Charges',
    'Sponsorship Fees - Navodaya',
    'Sponsorship Fees - Karnataka Adarsh Odia Association',
    'Sponsorship Fees - Odia Seva Samithi',
    'Sponsorship Fees - Odia Youth Committee',
    'Sponsorship Fees - Psaowadurgapuja',
    'Sponsorship Fees - Utkal Youth',
    'Marketing Expenses - Google Ads',
    'Marketing Expenses - Facebook Ads',
    'Marketing Expenses - LinkedIn Ads',
    'Marketing Expenses - Lead Squared CRM',
    'Marketing Expenses - Digital Ocean',
    'Marketing Expenses - AI Dialer',
    'Marketing Expenses - Servetel Communications',
    'Marketing Expenses - Siteground Hosting',
    'Marketing Expenses - VMC Technologies',
    'Marketing Expenses - WhatsApp API',
    'Marketing Expenses - Zoom Video',
    'Marketing Expenses - Naukri Portal',
    'Marketing Expenses - Metaverse Expo',
    'Marketing Expenses - Nextgen Technology',
    'Marketing Expenses - Pamphlet Distribution',
    'Faculty Fees - Ayushkant',
    'Faculty Fees - Debendra Debadutta Das',
    'Faculty Fees - Ganesh Rath',
    'Faculty Fees - Kuldeep Shahi',
    'Faculty Fees - Mradul Jain',
    'Faculty Fees - Prabin Mohanty',
    'Faculty Fees - Raj Narayan Birje',
    'Faculty Fees - Suresh Reddy',
    'Faculty Fees - Venkat Reddy Ko',
  ],
  'Administration Expenses': [
    'Office Rent',
    'Office Expenses',
    'Office Maintenance',
    'Annual Function Expenses',
    'Business Promotion Expenses',
    'Consultancy Charges',
    'Courier Expenses',
    'Electricity Charges',
    'Fuel Expenses',
    'Internet Expenses',
    'IT Expenses',
    'Local Conveyance Expense',
    'Miscellaneous Expenses',
    'Printing & Stationery',
    'Repairs and Maintenance',
    'Telephone & Communication Expenses',
    'Travelling Expenses',
    'Web Hosting Charges',
    'Round Off',
  ],
  'Financial Expenses': [
    'Bank Charges',
    'Interest on Loan',
    'Interest on OD',
    'Interest on TDS',
    'Processing Fees',
    'Renewal Fees',
    'ROC filing fees',
    'Penalty on PF',
  ],
  'Human Resources Expenses': [
    'Salary expenses',
    'EPF Employer Contribution',
    'Employees Group Insurance',
    'Incentive/Bonus',
    'Referral Bonus',
    'Staff Welfare',
    'Other Deduction',
  ],
  'Depreciation & Amortization': ['Equipment Depreciation', 'Software Amortization'],
};
